<?php

namespace AppBundle\Repository;

/**
 * BestelregelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestelregelRepository extends \Doctrine\ORM\EntityRepository
{
}
